name: NAxios
favicon: null
layout_spectrum: 0.98238
typography_spectrum: 0.83622
title: The blog of Nathaniel Axios ( forever in beta state)
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b2a39'
    - '#ffffff'
    - '#b3af16'
    - '#dedd9c'
    - '#767f88'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
